### PR TITLE
test refactor proposal

### PR DESCRIPTION
**Pull request by benbrunton**
Please have a browse of this PR but don't feel obliged to merge. This is by no means a perfect submission, but it should serve to illustrate a few points.

1. The update to application code is purely organisational. I've not changed any *logic*.
2. The data module and controller modules now contain code that is (mostly) only concerned with fetching data and with organising it for rendering respectively.
3. The majority of the code in `tournament.spec.js` is concerned with arranging mocks to pass into the controller action. The tests themselves should not contain too much noise. (Difficult to achieve with asynchronous callback code like we are dealing with here)
4. Once your test coverage is good, you can refactor your logic with confidence 😃

### CODE REVIEW

**Comment by steveburton4** [comment]
I like it - it's a great point for the guys to start refactoring the other endpoints. It's moving more towards MVC style with the creation of the controllers. Gives an introduction to mocking too (you all remember this perfectly from my TDD workshop, yes?!).

I think when looking at the individual classes as well you could all try and clean the methods up a bit. Always try and remember single responsibility - one method does one thing and one thing only. If it's doing more, split it. Same with a class, it should have a defined singular reason for being.

Ben's tests will allow you to easily test the endpoints but you'll find it hard to test any logic within the controllers currently (rather than just the result of the endpoints) due to the size of some of the methods. There's not much logic in there currently, but it's something to consider as you write more code.

Obviously it would be good to split the DB stuff out too and leave that up to something else, which is passed in as a dependancy but I really don't think this needs to be done now!

I'm not going to complete the merge though as I think you as the team should do that 👍

**Comment by benbrunton** [comment]
😢

**Comment by Rohoolio** [comment]
She deemed your request unworthy....

**Comment by steveburton4** [comment]
Harsh...

Regards,
Steven Burton

________________________________

**Pull request closed without merging**
